name: Cargo build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      #- uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: -- #--include-ignored
      #- run: bin/test-compression.sh
      - run: cargo clean
      - run: rustup component add llvm-tools-preview
      - run: CARGO_INCREMENTAL="0" RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort" cargo build
      - run: CARGO_INCREMENTAL="0" RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort" LLVM_PROFILE_FILE="serbzip-%p-%m.profraw" cargo test
      - run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - run: zip -0 ccov.zip `find . \( -name "YOUR_PROJECT_NAME*.gc*" \) -print`
      - run: ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - run: bash <(curl -s https://codecov.io/bash) -f lcov.info